"""empty message

Revision ID: 696bd4f3b7d7
Revises: ed5c8a27b286
Create Date: 2022-05-15 21:20:23.989756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '696bd4f3b7d7'
down_revision = 'ed5c8a27b286'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blog', sa.String(length=999999), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    # ### end Alembic commands ###
